name: Deploy GrowLux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/vhosts/meyssam.ir/httpdocs/GrowLux || exit 1
          if [ -d ".git" ]; then
            git pull origin main
          else
            rm -rf * .[^.]* 2>/dev/null
            git clone https://github.com/MeyssamMolaei/GrowLux .
          fi
          chmod -R 755 .